"use client"

import Link from "next/link"
import Image from "next/image"
import {Book} from "@/app/types"
import styles from "./style.module.css"
import {get_books} from "@/app/api/get_books"
import {useQuery} from "@tanstack/react-query"
import Navigation from "@/app/components/navigation/component"

export default function AIBooks() {
	const { data } = useQuery<Book[]>({
		queryKey: ["books"],
		queryFn: () => get_books(),
		staleTime: 5 * 1000,
	})

	return (
		<>
			<Navigation />
			<h2 className={styles.routeHeading}>Books generated by <Image alt="ai-icon" width={100} height={50} src="/ai-icon.png" /></h2>
			<div className={styles.books}>
				{data?.map((book, i) => (
					<div className={styles.book} key={i}>
						<h2 className={styles.title}>{book.title}</h2>
						<div className={styles.bookCover}>
							<Image className={styles.bookCoverImg} alt="book cover" width={200} height={250} src="/book-cover.png"/>
							<Link className={styles.read} href={`ai-books/${book.title.split(" ").join("-")}`}>
								Read
							</Link>
						</div>
					</div>
				))}
			</div>
		</>
	)
}
