# Generated by Django 4.2.6 on 2023-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookgenres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.URLField(default='https://en.wikipedia.org/wiki/Genre#/media/File:Books_and_Scroll_Ornament_with_Open_Book.png', max_length=300),
        ),
    ]
